//! MCP (Model Context Protocol) server module.
//!
//! Built on the official `rmcp` SDK. Tool schemas are generated from the `params` structs
//! (`#[derive(JsonSchema)]`) and dispatch is generated by `#[tool_router]` in `tools` — a
//! single source of truth, no hand-written JSON schemas. `server` wires the router into a
//! `ServerHandler` (adding `qmdc://` resources) and runs it over stdio.

pub mod params;
pub mod resources;
pub mod server;
pub mod tools;

pub use server::run_mcp_server;
