//! MCP server entry point (rmcp-based).
//!
//! The tool surface lives in [`super::tools::QmdcServer`] (generated by `#[tool_router]`).
//! This module wires that router into a `ServerHandler` (adding resource support) and starts
//! the server over the stdio transport.

use rmcp::model::{
    ListResourcesResult, PaginatedRequestParam, ReadResourceRequestParam, ReadResourceResult,
    ServerCapabilities, ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::{tool_handler, ErrorData as McpError, RoleServer, ServerHandler, ServiceExt};

use super::resources::{read_resource, resource_list};
use super::tools::QmdcServer;

const SERVER_NAME: &str = "qmdc-mcp";
const SERVER_VERSION: &str = env!("CARGO_PKG_VERSION");

#[tool_handler]
impl ServerHandler for QmdcServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            server_info: rmcp::model::Implementation {
                name: SERVER_NAME.to_string(),
                version: SERVER_VERSION.to_string(),
                ..Default::default()
            },
            capabilities: ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
            instructions: Some(
                "QMDC workspace tools: locate/describe/search objects, find references, \
                 rename (diff-only), validate, query SQL, traverse the reference graph, and \
                 read qmdc:// resources. Every tool resolves the workspace from a `path` argument."
                    .to_string(),
            ),
            ..Default::default()
        }
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult {
            resources: resource_list(),
            next_cursor: None,
        })
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        Ok(read_resource(&request.uri))
    }
}

/// Run the MCP server on stdio transport (production entry point).
///
/// `force_root`, when provided, restricts every operation to paths within that directory
/// (INV-1 fail-closed boundary, see `core::index_seam::enforce_force_root`).
pub async fn run_mcp_server(force_root: Option<std::path::PathBuf>) {
    if let Some(root) = force_root {
        crate::core::index_seam::set_force_root(root);
    }

    let service = QmdcServer::new().serve(rmcp::transport::stdio()).await;
    match service {
        Ok(service) => {
            if let Err(e) = service.waiting().await {
                eprintln!("[mcp] service error: {e}");
            }
        }
        Err(e) => {
            eprintln!("[mcp] failed to start server: {e}");
        }
    }
}

// Re-export so existing imports of the router type keep working.
pub use super::tools::QmdcServer as Server;
